# Generated by Django 5.1.5 on 2025-05-04 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
